package com.dynamodb.main.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Getter
@Setter
@RequiredArgsConstructor
@DynamoDBTable(tableName = "-dp-user-traits-store")
public class UserTrait {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBRangeKey
    private String traitKey;

    @DynamoDBAttribute
    private String traitValue;
}
